image: mcr.microsoft.com/playwright:v1.42.1-jammy

stages:
  - test

variables:
  TEST_ENV: "stg"
  RUN_TIMES: "1"
  ENV: "stg"

run_fullflow_tests:
  stage: test
  tags:
    - ci-v2

  script:
    - echo "Environment: $TEST_ENV"
    - echo "Run times: $RUN_TIMES"
    - npm ci
    - npx playwright install
    - echo "Running Playwright tests on $ENV"
    - npx playwright test flows/fullflow.spec.ts
    - npx playwright test tests/fullflow.spec.ts

  artifacts:
    when: always
    paths:
      - playwright-report/
      - fullflow-summary.html
    expire_in: 7 days